logging:
  level:
    org:
      springframework:
        data: debug
        web: debug

spring:
  data:
    mongodb:
      database: demo
#      uri: mongodb://localhost:27017,localhost:27018,localhost:27019/?replicaSet=rs0